In [ ]:
# this notebook will prepare data to visualize on chart
# create markers
import json
import pandas as pd
import gc
from pathlib import Path
import numpy as np

DATA_PATH = Path.cwd().parents[1] / "data" / "bigData" / "BTCUSD-15m.json"

with open(DATA_PATH) as f:
    file = json.load(f)

ohlcv = file["ohlcv"]  # list of [timestamp, open, high, low, close, volume]
del file  # free the rest of the JSON (symbol, onchart, etc.), , preserve RAM

df = pd.DataFrame(ohlcv, columns=["timestamp", "open", "high", "low", "close", "vol"])
del ohlcv  # free the Python list-of-lists, preserve RAM
gc.collect()

# Halve memory: float64 -> float32 for price/volume columns
df[["open", "high", "low", "close", "vol"]] = df[["open", "high", "low", "close", "vol"]].astype("float32")

# print(df.head())
# beware  was truncated by the NotebookEdit tool on the previous write
print(f"Shape: {df.shape} | Memory: {df.memory_usage(deep=True).sum()/ 1e6:.2f} MB")

Shape: (70930, 6) | Memory: 1.99 MB

In [3]:
df.head()
# save as JSONL
# OUT_PATH = Path.cwd().parents[1] / "data" / "bigData" / "BTCUSD-15m.jsonl"
# df.to_json(OUT_PATH, orient="records", lines=True)
# print(f"Saved {len(df)} rows to {OUT_PATH}")

,timestamp,open,high,low,close,vol
0,1708659900000,51099.929688,51120.000000,51052.199219,51100.000000,209.838379
1,1708660800000,51100.000000,51106.871094,51003.000000,51091.859375,230.937881
2,1708661700000,51091.871094,51236.640625,51031.101562,51236.640625,333.208618
3,1708662600000,51236.628906,51321.921875,51183.210938,51224.031250,284.106201
4,1708663500000,51224.039062,51254.199219,51195.839844,51219.589844,169.352463

# Common Methods for Normalizing OHLC Data
- Min-Max Scaling (Rolling Window)
- Log Returns / Percentage Change
- Standardization (Z-score)
- Base-Price Normalization : divide all by base

In [5]:
def _fix_break_of_structure(isXXX, isSource, high, low):
    """
    Ensure isXXX alternates strictly between 1 and -1.
    On a break (1,1 or -1,-1), insert the best counter swing between the two offending positions,
    but ONLY if it is structurally valid:
      - Inserting a  1 (high): candidate high must be > max(low[p1],  low[p2])
      - Inserting a -1 (low) : candidate low  must be < min(high[p1], high[p2])
    If no valid candidate exists, remove the less extreme of the two duplicates instead.
    """
    changed = True
    while changed:
        changed = False
        non_zero = np.where(isXXX != 0)[0]

        for i in range(1, len(non_zero)):
            p1, p2 = non_zero[i - 1], non_zero[i]
            v1, v2 = isXXX[p1], isXXX[p2]

            if v1 != v2:
                continue

            counter    = np.int8(-v1)
            candidates = np.arange(p1 + 1, p2)

            inserted = False
            if len(candidates) > 0:
                source_cands = candidates[isSource[candidates] == counter]
                pool = source_cands if len(source_cands) > 0 else candidates

                if counter == -1:
                    # Inserting a low: must dip below both surrounding highs
                    threshold  = min(high[p1], high[p2])
                    valid_pool = pool[low[pool] < threshold]
                else:
                    # Inserting a high: must rise above both surrounding lows
                    threshold  = max(low[p1], low[p2])
                    valid_pool = pool[high[pool] > threshold]

                if len(valid_pool) > 0:
                    best = (valid_pool[np.argmin(low[valid_pool])]
                            if counter == -1
                            else valid_pool[np.argmax(high[valid_pool])])
                    isXXX[best] = counter
                    inserted = True

            if not inserted:
                # No structurally valid candidate — drop the less extreme duplicate
                if v1 == 1:   # two highs: keep the higher one
                    isXXX[p1 if high[p1] < high[p2] else p2] = 0
                else:          # two lows: keep the lower one
                    isXXX[p1 if low[p1]  > low[p2] else p2] = 0

            changed = True
            break  # restart after each change

    return isXXX

In [6]:
def _fix_price_order(isXXX, high, low):
    """
    Fix price ordering violations by inserting 2 bridging marks instead of removing.
    For ITR/LTR: inserted marks need not be original swing points.
    Falls back to removal only if no valid bridge candidates exist.
    """
    changed = True
    while changed:
        changed = False
        non_zero = np.where(isXXX != 0)[0]

        for i in range(1, len(non_zero)):
            p1, p2 = non_zero[i-1], non_zero[i]
            v1, v2 = isXXX[p1], isXXX[p2]

            if v1 == 1 and v2 == -1 and low[p2] >= high[p1]:
                # Need a real low then a real high between p1 and p2
                cands = np.arange(p1 + 1, p2)
                valid_lows = cands[low[cands] < high[p1]]
                if len(valid_lows) > 0:
                    best_low = valid_lows[np.argmin(low[valid_lows])]
                    after = np.arange(best_low + 1, p2)
                    valid_highs = after[high[after] > low[best_low]]
                    if len(valid_highs) > 0:
                        best_high = valid_highs[np.argmax(high[valid_highs])]
                        isXXX[best_low]  = -1
                        isXXX[best_high] = 1
                        changed = True
                        break
                # fallback: remove the bad low
                isXXX[p2] = 0
                changed = True
                break

            elif v1 == -1 and v2 == 1 and high[p2] <= low[p1]:
                # Need a real high then a real low between p1 and p2
                cands = np.arange(p1 + 1, p2)
                valid_highs = cands[high[cands] > low[p1]]
                if len(valid_highs) > 0:
                    best_high = valid_highs[np.argmax(high[valid_highs])]
                    after = np.arange(best_high + 1, p2)
                    valid_lows = after[low[after] < high[best_high]]
                    if len(valid_lows) > 0:
                        best_low = valid_lows[np.argmin(low[valid_lows])]
                        isXXX[best_high] = 1
                        isXXX[best_low]  = -1
                        changed = True
                        break
                # fallback: remove the bad high
                isXXX[p2] = 0
                changed = True
                break

    return isXXX

In [ ]:
# varsion 1
def strHunt(df, window=4):
    n = len(df)
    df = df.copy()

    high = df['high'].values
    low  = df['low'].values

    isSTR = np.zeros(n, dtype=np.int8)

    # --- First window: can't look backward, so determine direction from the span ---
    # if n > window + 1:
    #     diff = high[window + 1] - low[0]
    #     if diff > 0:
    #         isSTR[0] = -1   # start of bullish move → mark as low
    #     elif diff < 0:
    #         isSTR[0] = 1    # start of bearish move → mark as high

    # --- First window: method 2 just mark 0

    # --- Main loop: candles with a full symmetric window on both sides ---
    # Stop at n-window so the last `window` candles remain 0
    for i in range(window, n - window):
        win_high = high[i - window : i + window + 1]
        win_low  = low [i - window : i + window + 1]

        is_swing_high = high[i] >= win_high.max()   # local maximum
        is_swing_low  = low[i]  <= win_low.min()    # local minimum

        if is_swing_high and not is_swing_low:
            isSTR[i] = 1    # confirmed swing high
        elif is_swing_low and not is_swing_high:
            isSTR[i] = -1   # confirmed swing low
        # neither → stays 0
        # both, liquidity swept on both high and low → stays 0
        

    isSTR = _fix_break_of_structure(isSTR, isSTR, high, low)
    isSTR = _fix_price_order(isSTR, high, low)

    df['isSTR'] = isSTR
    return df

# execute -- 
df = strHunt(df)

In [7]:
def itrHunt(df, group=3):
    # there must be isSTR column presented first
    # search for intermediate term range
    # group params input must be odd number (has middle point)
    # to qualify, the middle swing high must be the highest among `group` consecutive swing HIGHS
    # to qualify, the middle swing low must be the lowest among `group` consecutive swing LOWS
    # highs are compared against highs only, lows against lows only
    # (requires at least 1,1,1 or -1,-1,-1 in isSTR for a valid group comparison)

    df = df.copy()
    n = len(df)

    high  = df['high'].values
    low   = df['low'].values
    isSTR = df['isSTR'].values
    isITR = np.zeros(n, dtype=np.int8)

    # Separate by type — compare like with like
    high_pos = np.where(isSTR == 1)[0]   # all swing high positions
    low_pos  = np.where(isSTR == -1)[0]  # all swing low positions

    half = group // 2  # e.g. group=3 → half=1

    # ITR swing highs: middle must be highest among `group` consecutive swing highs
    for j in range(half, len(high_pos) - half):
        group_pos = high_pos[j - half : j + half + 1]
        mid_pos   = high_pos[j]
        if high[mid_pos] >= high[group_pos].max():
            isITR[mid_pos] = 1

    # ITR swing lows: middle must be lowest among `group` consecutive swing lows
    for j in range(half, len(low_pos) - half):
        group_pos = low_pos[j - half : j + half + 1]
        mid_pos   = low_pos[j]
        if low[mid_pos] <= low[group_pos].min():
            isITR[mid_pos] = -1

    # handle break of structure case
    isITR = _fix_break_of_structure(isITR, isSTR, high, low)
    # handle exception case : price ordering
    isITR = _fix_price_order(isITR, high, low)


    df['isITR'] = isITR
    return df


# execute --
df = itrHunt(df)

In [8]:
def ltrHunt(df, group=3):
    # there must be isITR column presented first
    # search for long term range
    # highs are compared against highs only, lows against lows only
    # (requires at least 1,1,1 or -1,-1,-1 in isITR for a valid group comparison)

    df = df.copy()
    n = len(df)

    high  = df['high'].values
    low   = df['low'].values
    isITR = df['isITR'].values
    isLTR = np.zeros(n, dtype=np.int8)

    # Separate by type — compare like with like
    high_pos = np.where(isITR == 1)[0]
    low_pos  = np.where(isITR == -1)[0]

    half = group // 2

    for j in range(half, len(high_pos) - half):
        group_pos = high_pos[j - half : j + half + 1]
        mid_pos   = high_pos[j]
        if high[mid_pos] >= high[group_pos].max():
            isLTR[mid_pos] = 1

    for j in range(half, len(low_pos) - half):
        group_pos = low_pos[j - half : j + half + 1]
        mid_pos   = low_pos[j]
        if low[mid_pos] <= low[group_pos].min():
            isLTR[mid_pos] = -1

    # handle break of structure case
    isLTR = _fix_break_of_structure(isLTR, isITR, high, low)
    # handle exception case : price ordering
    isLTR = _fix_price_order(isLTR, high, low)


    df['isLTR'] = isLTR
    return df


# execute --
df = ltrHunt(df)

In [9]:
# check point - preview data
df.tail()

,timestamp,open,high,low,close,vol,isSTR,isITR,isLTR
70925,1772492400000,69440.476562,69479.578125,69215.398438,69223.242188,121.096069,0,0,0
70926,1772493300000,69223.250000,69261.687500,68990.976562,69002.929688,223.747665,0,0,0
70927,1772494200000,69002.921875,69014.257812,68758.398438,68796.859375,195.868637,0,0,0
70928,1772495100000,68796.859375,68965.671875,68740.000000,68830.062500,97.017410,0,0,0
70929,1772496000000,68830.062500,69004.398438,68750.679688,68809.992188,168.970734,0,0,0

In [ ]:
def validate_markers(df, col):
    """
    Validate a marker column (e.g. 'isITR', 'isLTR') across the entire DataFrame.

    Checks two invariants:
      1. BOS (Break-of-Structure): consecutive non-zero entries must alternate sign (no 1,1 or -1,-1).
      2. Price order: after a high (1), the next low (-1) must be strictly below it,
         and after a low (-1), the next high (1) must be strictly above it.

    Returns
    -------
    dict with keys:
        'bos_violations'   : DataFrame of rows where sign repeats
        'order_violations' : DataFrame of rows where price order is broken
        'is_valid'         : True only if both checks pass
    """
    rows = df[df[col] != 0][['timestamp', 'high', 'low', col]].copy()
    rows['price_at_mark'] = rows.apply(
        lambda r: r['high'] if r[col] == 1 else r['low'], axis=1
    )

    vals = rows[col].values

    # --- BOS check: consecutive same-sign entries ---
    bos_mask = [False] + [vals[i] == vals[i - 1] for i in range(1, len(vals))]
    bos_violations = rows[bos_mask]

    # --- Price order check ---
    order_fail_idx = []
    for i in range(1, len(rows)):
        prev = rows.iloc[i - 1]
        curr = rows.iloc[i]
        if curr[col] == 1:          # current is a high → must be above prev low
            if curr['high'] <= prev['low']:
                order_fail_idx.append(rows.index[i])
        else:                        # current is a low → must be below prev high
            if curr['low'] >= prev['high']:
                order_fail_idx.append(rows.index[i])
    order_violations = rows.loc[order_fail_idx]

    # --- Print summary ---
    label = col
    total = len(rows)
    print(f"=== {label} validation ({total} marks across full dataset) ===")

    if len(bos_violations):
        print(f"  BOS violations : {len(bos_violations)}")
        print(bos_violations[['timestamp', 'high', 'low', col, 'price_at_mark']].to_string())
    else:
        print("  BOS violations : 0  — alternation OK")

    if len(order_violations):
        print(f"  Order violations: {len(order_violations)}")
        print(order_violations[['timestamp', 'high', 'low', col, 'price_at_mark']].to_string())
    else:
        print("  Order violations: 0  — price ordering OK")

    is_valid = len(bos_violations) == 0 and len(order_violations) == 0
    print(f"  Valid: {is_valid}\n")

    return {
        'bos_violations':   bos_violations,
        'order_violations': order_violations,
        'is_valid':         is_valid,
    }

=== isSTR validation (10886 marks across full dataset) ===
  BOS violations : 2048
           timestamp           high            low  isSTR  price_at_mark
38     1708694100000   51042.429688   50925.019531     -1   50925.019531
50     1708704900000   50877.839844   50629.328125     -1   50629.328125
78     1708730100000   50805.578125   50521.000000     -1   50521.000000
94     1708744500000   50782.710938   50682.000000     -1   50682.000000
131    1708777800000   51065.140625   51032.339844     -1   51032.339844
145    1708790400000   51166.000000   51094.988281     -1   51094.988281
170    1708812900000   51666.000000   51605.558594      1   51666.000000
182    1708823700000   51513.539062   51438.878906     -1   51438.878906
195    1708835400000   51561.101562   51509.000000     -1   51509.000000
210    1708848900000   51777.640625   51729.988281      1   51777.640625
221    1708858800000   51627.179688   51553.289062     -1   51553.289062
229    1708866000000   51693.589844   51569.019531      1   51693.589844
267    1708900200000   51860.000000   51819.500000      1   51860.000000
275    1708907400000   51796.500000   51675.929688      1   51796.500000
297    1708927200000   51598.058594   51541.101562      1   51598.058594
337    1708963200000   53647.710938   52753.281250      1   53647.710938
353    1708977600000   54910.000000   54373.828125      1   54910.000000
362    1708985700000   54807.398438   54501.101562      1   54807.398438
383    1709004600000   56530.089844   56368.429688      1   56530.089844
416    1709034300000   56527.800781   56321.101562     -1   56321.101562
469    1709082000000   57101.101562   56878.980469      1   57101.101562
484    1709095500000   57271.441406   57060.019531      1   57271.441406
511    1709119800000   59494.058594   59134.000000      1   59494.058594
534    1709140500000   64000.000000   61130.000000      1   64000.000000
549    1709154000000   60510.000000   59797.570312     -1   59797.570312
588    1709189100000   63676.351562   62883.511719      1   63676.351562
614    1709212500000   62813.878906   62051.109375     -1   62051.109375
636    1709232300000   60841.101562   60364.699219     -1   60364.699219
689    1709280000000   61532.871094   61316.671875     -1   61316.671875
698    1709288100000   62188.000000   61917.660156      1   62188.000000
740    1709325900000   63114.230469   62414.441406      1   63114.230469
786    1709367300000   61959.820312   61779.609375     -1   61779.609375
833    1709409600000   62200.000000   61821.101562      1   62200.000000
845    1709420400000   61917.011719   61685.011719     -1   61685.011719
859    1709433000000   61793.210938   61642.390625     -1   61642.390625
875    1709447400000   62043.000000   61900.000000      1   62043.000000
913    1709481600000   62312.929688   62088.000000     -1   62088.000000
923    1709490600000   62863.679688   62595.281250      1   62863.679688
938    1709504100000   63231.878906   62820.011719      1   63231.878906
941    1709506800000   62886.910156   62700.000000     -1   62700.000000
953    1709517600000   63540.000000   63100.000000     -1   63100.000000
996    1709556300000   65157.140625   64868.660156     -1   64868.660156
1001   1709560800000   65275.031250   64533.671875     -1   64533.671875
1048   1709603100000   68686.796875   68244.343750      1   68686.796875
1101   1709650800000   69000.000000   67100.000000      1   69000.000000
1171   1709713800000   67641.101562   66776.046875      1   67641.101562
1237   1709773200000   66241.101562   65551.000000     -1   65551.000000
1256   1709790300000   65870.687500   65662.718750     -1   65662.718750
1266   1709799300000   67014.000000   66750.000000      1   67014.000000
1284   1709815500000   66753.929688   66575.523438     -1   66575.523438
1302   1709831700000   67980.000000   67571.648438      1   67980.000000
1309   1709838000000   67848.476562   67590.000000      1   67848.476562
1329   1709856000000   66883.453125   66757.000000     -1   66757.000000
1342   1709867700000   67254.218750   67069.890625      1   67254.218750
1363   1709886600000   67337.390625   67038.710938     -1   67038.710938
1377   1709899200000   67775.039062   67497.203125      1   67775.039062
1432   1709948700000   68020.000000   67861.101562     -1   67861.101562
1453   1709967600000   68541.101562   68396.328125      1   68541.101562
1467   1709980200000   68176.000000   67933.929688     -1   67933.929688
1477   1709989200000   68521.101562   68362.039062      1   68521.101562
1493   1710003600000   68171.640625   68000.000000     -1   68000.000000
1494   1710004500000   68121.406250   68000.000000     -1   68000.000000
1510   1710018900000   68366.046875   68209.593750     -1   68209.593750
1517   1710025200000   68433.171875   68310.000000      1   68433.171875
1518   1710026100000   68433.171875   68310.000000      1   68433.171875
1559   1710063000000   69756.000000   69162.000000     -1   69162.000000
1592   1710092700000   69600.000000   69411.070312      1   69600.000000
1656   1710150300000   71831.992188   71501.203125      1   71831.992188
1670   1710162900000   72380.000000   71928.007812      1   72380.000000
1689   1710180000000   72499.992188   72180.000000     -1   72180.000000
1782   1710263700000   69940.000000   68620.820312     -1   68620.820312
1815   1710293400000   72100.000000   71757.046875      1   72100.000000
1822   1710299700000   72217.789062   71999.882812      1   72217.789062
1828   1710305100000   72210.000000   72141.101562      1   72210.000000
1877   1710349200000   73180.000000   72845.000000      1   73180.000000
1883   1710354600000   73263.992188   72944.000000      1   73263.992188
1890   1710360900000   73410.218750   73161.382812      1   73410.218750
1895   1710365400000   73361.007812   72940.000000      1   73361.007812
1953   1710417600000   73047.156250   72820.000000      1   73047.156250
1997   1710457200000   71709.898438   71401.101562      1   71709.898438
2019   1710477000000   68278.406250   66904.976562     -1   66904.976562
2055   1710509400000   68285.203125   67424.789062     -1   67424.789062
2061   1710514800000   68746.687500   68310.460938      1   68746.687500
2077   1710529200000   70650.000000   70081.101562      1   70650.000000
2153   1710597600000   68146.398438   67524.000000     -1   67524.000000
2172   1710614700000   67102.507812   66670.000000     -1   66670.000000
2180   1710621900000   67538.492188   67107.546875      1   67538.492188
2187   1710628200000   66786.437500   66477.000000      1   66786.437500
2259   1710693000000   68385.820312   68045.500000      1   68385.820312
2264   1710697500000   68693.750000   68180.000000      1   68693.750000
2341   1710766800000   68627.812500   68250.000000      1   68627.812500
2365   1710788400000   67187.171875   66870.953125     -1   66870.953125
2375   1710797400000   67896.546875   67517.726562      1   67896.546875
2414   1710832500000   64528.000000   63577.000000     -1   63577.000000
2421   1710838800000   63808.218750   62982.800781     -1   62982.800781
2472   1710884700000   64109.980469   63691.890625      1   64109.980469
2530   1710936900000   64353.570312   63683.871094      1   64353.570312
2592   1710992700000   66979.070312   66340.000000     -1   66340.000000
2598   1710998100000   66550.773438   66072.203125     -1   66072.203125
2610   1711008900000   67659.531250   67300.000000      1   67659.531250
2657   1711051200000   65489.609375   64529.011719     -1   64529.011719
2665   1711058400000   65857.273438   65600.000000      1   65857.273438
2697   1711087200000   66649.617188   66337.773438      1   66649.617188
2732   1711118700000   63088.480469   62601.109375     -1   62601.109375
2752   1711136700000   64126.089844   63772.429688      1   64126.089844
2777   1711159200000   64374.910156   63910.000000      1   64374.910156
2839   1711215000000   65999.000000   65627.070312      1   65999.000000
2864   1711237500000   64450.000000   63861.660156     -1   63861.660156
2883   1711254600000   64061.191406   63772.289062     -1   63772.289062
2908   1711277100000   65368.660156   65090.000000      1   65368.660156
2917   1711285200000   65825.000000   65450.019531      1   65825.000000
2929   1711296000000   65838.882812   65596.000000      1   65838.882812
2958   1711322100000   67628.687500   67300.773438      1   67628.687500
2992   1711352700000   67024.000000   66710.000000     -1   66710.000000
3008   1711367100000   66887.640625   66760.000000     -1   66760.000000
3041   1711396800000   71150.000000   70737.382812      1   71150.000000
3073   1711425600000   70665.828125   70401.109375      1   70665.828125
3154   1711498500000   70119.398438   69840.000000     -1   69840.000000
3217   1711555200000   69310.000000   68359.179688     -1   68359.179688
3247   1711582200000   69202.000000   69072.398438     -1   69072.398438
3385   1711706400000   69883.578125   69566.000000     -1   69566.000000
3412   1711730700000   69498.000000   69078.617188     -1   69078.617188
3453   1711767600000   70042.187500   69906.132812      1   70042.187500
3527   1711834200000   69746.257812   69621.968750     -1   69621.968750
3579   1711881000000   70281.406250   70214.523438     -1   70214.523438
3703   1711992600000   68524.726562   68201.117188     -1   68201.117188
3719   1712007000000   69900.000000   69631.109375      1   69900.000000
3727   1712014200000   69876.039062   69758.992188      1   69876.039062
3739   1712025000000   68536.000000   66000.000000     -1   66000.000000
3750   1712034900000   66557.750000   66120.750000     -1   66120.750000
3756   1712040300000   67120.000000   66830.156250      1   67120.000000
3775   1712057400000   65536.921875   65075.000000     -1   65075.000000
3783   1712064600000   65116.101562   64588.578125     -1   64588.578125
3807   1712086200000   66200.000000   65851.070312      1   66200.000000
3843   1712118600000   66478.593750   66216.000000      1   66478.593750
3879   1712151000000   65957.101562   65635.007812     -1   65635.007812
3938   1712204100000   65548.039062   65064.519531     -1   65064.519531
3962   1712225700000   66468.992188   66205.203125      1   66468.992188
3986   1712247300000   68188.000000   67678.398438      1   68188.000000
3993   1712253600000   69309.906250   68705.882812      1   69309.906250
3999   1712259000000   69086.226562   68684.062500      1   69086.226562
4007   1712266200000   67955.976562   67495.000000     -1   67495.000000
4081   1712332800000   68380.000000   68034.843750      1   68380.000000
4144   1712389500000   68189.328125   67953.148438      1   68189.328125
4157   1712401200000   67904.351562   67717.218750      1   67904.351562
4163   1712406600000   67796.687500   67663.226562      1   67796.687500
4189   1712430000000   68415.000000   68218.000000      1   68415.000000
4191   1712431800000   68415.000000   68290.898438      1   68415.000000
4201   1712440800000   68539.187500   68286.328125     -1   68286.328125
4217   1712455200000   69777.000000   69472.617188      1   69777.000000
4227   1712464200000   69278.578125   69053.968750     -1   69053.968750
4235   1712471400000   69298.679688   69110.812500     -1   69110.812500
4288   1712519100000   69320.000000   68849.773438     -1   68849.773438
4452   1712666700000   70977.000000   70690.000000      1   70977.000000
4469   1712682000000   68791.757812   68210.000000     -1   68210.000000
4477   1712689200000   68879.226562   68656.078125     -1   68656.078125
4552   1712756700000   68313.101562   67518.000000     -1   67518.000000
4566   1712769300000   69910.960938   69195.851562      1   69910.960938
4616   1712814300000   70600.000000   70444.000000     -1   70444.000000
4659   1712853000000   69845.757812   69574.882812     -1   69574.882812
4695   1712885400000   70258.187500   70113.601562     -1   70113.601562
4719   1712907000000   70865.929688   70566.023438     -1   70566.023438
4758   1712942100000   68711.992188   67444.000000     -1   67444.000000
4763   1712946600000   67889.898438   65086.859375     -1   65086.859375
4813   1712991600000   67563.656250   67366.632812      1   67563.656250
4820   1712997900000   67285.382812   67090.828125     -1   67090.828125
4893   1713063600000   63150.000000   62134.000000     -1   62134.000000
4966   1713129300000   63815.148438   63326.421875     -1   63326.421875
4987   1713148200000   65272.398438   64937.011719     -1   64937.011719
5021   1713178800000   66720.640625   66191.476562      1   66720.640625
5149   1713294000000   63094.800781   62843.921875      1   63094.800781
5166   1713309300000   63876.640625   63690.019531      1   63876.640625
5177   1713319200000   64295.000000   63989.160156      1   64295.000000
5186   1713327300000   63817.179688   63672.261719     -1   63672.261719
5209   1713348000000   63338.718750   62752.308594     -1   62752.308594
5252   1713386700000   61245.929688   60777.000000     -1   60777.000000
5261   1713394800000   61763.070312   61544.109375      1   61763.070312
5310   1713438900000   63072.269531   62400.000000      1   63072.269531
5337   1713463200000   62907.679688   62310.031250     -1   62310.031250
5426   1713543300000   64276.621094   63506.570312     -1   63506.570312
5444   1713559500000   64044.121094   63677.359375     -1   63677.359375
5496   1713606300000   63646.000000   63277.000000     -1   63277.000000
5583   1713684600000   65086.121094   64899.839844     -1   64899.839844
5654   1713748500000   65640.000000   64908.390625      1   65640.000000
5672   1713764700000   66414.812500   66064.453125      1   66414.812500
5677   1713769200000   66479.796875   66097.359375      1   66479.796875
5683   1713774600000   66204.437500   66035.171875      1   66204.437500
5703   1713792600000   66109.398438   65693.976562     -1   65693.976562
5796   1713876300000   66134.921875   65765.812500     -1   65765.812500
5922   1713989700000   64018.449219   63606.058594     -1   63606.058594
5940   1714005900000   64741.468750   64538.000000      1   64741.468750
5958   1714022100000   64234.148438   64025.500000     -1   64025.500000
6010   1714068900000   64975.000000   64649.988281      1   64975.000000
6017   1714075200000   64992.000000   64489.300781     -1   64489.300781
6029   1714086000000   64747.121094   64469.988281      1   64747.121094
6062   1714115700000   64610.820312   64279.570312      1   64610.820312
6120   1714167900000   64080.558594   63949.199219      1   64080.558594
6147   1714192200000   63175.000000   63020.281250      1   63175.000000
6155   1714199400000   63024.511719   62865.460938     -1   62865.460938
6173   1714215600000   62857.148438   62673.371094     -1   62673.371094
6186   1714227300000   63408.531250   63154.101562      1   63408.531250
6197   1714237200000   62866.519531   62750.000000     -1   62750.000000
6238   1714274100000   64370.000000   64026.218750      1   64370.000000
6266   1714299300000   63645.511719   63345.550781     -1   63345.550781
6272   1714304700000   63503.699219   63394.679688     -1   63394.679688
6300   1714329900000   63976.000000   63762.000000      1   63976.000000
6317   1714345200000   63151.058594   62781.000000     -1   62781.000000
6327   1714354200000   63367.050781   63167.691406      1   63367.050781
6343   1714368600000   62403.750000   62059.269531     -1   62059.269531
6348   1714373100000   62266.820312   61923.128906     -1   61923.128906
6362   1714385700000   62673.179688   62506.050781      1   62673.179688
6373   1714395600000   62698.550781   62511.429688      1   62698.550781
6439   1714455000000   63376.019531   63069.679688     -1   63069.679688
6465   1714478400000   61288.699219   60737.449219     -1   60737.449219
6474   1714486500000   60934.480469   60546.218750     -1   60546.218750
6512   1714520700000   60924.160156   60631.179688      1   60924.160156
6522   1714529700000   59871.101562   59590.000000     -1   59590.000000
6651   1714645800000   57776.191406   57561.140625     -1   57561.140625
6689   1714680000000   59431.101562   59191.660156      1   59431.101562
6700   1714689900000   59454.171875   59256.859375      1   59454.171875
6824   1714801500000   63450.000000   63124.539062      1   63450.000000
6840   1714815900000   63179.808594   63055.550781     -1   63055.550781
6881   1714852800000   64240.761719   63921.171875      1   64240.761719
6892   1714862700000   63720.699219   63569.988281     -1   63569.988281
6979   1714941000000   63724.000000   63582.078125     -1   63582.078125
7026   1714983300000   65500.000000   64462.480469      1   65500.000000
7028   1714985100000   65500.000000   65064.160156      1   65500.000000
7044   1714999500000   63785.589844   63343.859375     -1   63343.859375
7136   1715082300000   63620.871094   63358.000000     -1   63358.000000
7182   1715123700000   62446.351562   62261.000000     -1   62261.000000
7198   1715138100000   62780.230469   62588.000000     -1   62588.000000
7210   1715148900000   62540.000000   62135.480469     -1   62135.480469
7216   1715154300000   62359.988281   62020.089844     -1   62020.089844
7239   1715175000000   62087.449219   61761.000000     -1   61761.000000
7325   1715252400000   60956.921875   60630.000000     -1   60630.000000
7394   1715314500000   63008.000000   62850.000000      1   63008.000000
7441   1715356800000   61147.000000   60255.000000     -1   60255.000000
7448   1715363100000   60635.121094   60187.121094     -1   60187.121094
7505   1715414400000   61058.750000   60897.148438      1   61058.750000
7513   1715421600000   60904.429688   60850.000000      1   60904.429688
7524   1715431500000   60758.828125   60643.941406     -1   60643.941406
7545   1715450400000   61110.011719   61016.000000     -1   61016.000000
7588   1715489100000   61120.000000   61006.011719      1   61120.000000
7619   1715517000000   61168.031250   61090.000000     -1   61090.000000
7628   1715525100000   61186.628906   61124.769531     -1   61124.769531
7646   1715541300000   61355.539062   61209.589844     -1   61209.589844
7654   1715548500000   61310.000000   60910.578125     -1   60910.578125
7714   1715602500000   62749.769531   62399.351562     -1   62399.351562
7719   1715607000000   62845.000000   62600.789062     -1   62600.789062
7795   1715675400000   61925.210938   61697.050781     -1   61697.050781
7802   1715681700000   61676.890625   61520.890625     -1   61520.890625
7818   1715696100000   62030.238281   61142.769531     -1   61142.769531
7847   1715722200000   61776.121094   61472.410156     -1   61472.410156
7922   1715789700000   65150.000000   64758.011719      1   65150.000000
7935   1715801400000   66419.148438   65834.867188      1   66419.148438
7953   1715817600000   66666.000000   66206.500000      1   66666.000000
8023   1715880600000   64918.910156   64602.769531     -1   64602.769531
8048   1715903100000   65310.000000   65187.500000     -1   65187.500000
8093   1715943600000   66564.226562   66202.460938      1   66564.226562
8171   1716013800000   66817.859375   66730.000000     -1   66730.000000
8221   1716058800000   66820.000000   66771.757812     -1   66771.757812
8295   1716125400000   66940.000000   66677.000000     -1   66677.000000
8305   1716134400000   66990.000000   66850.210938      1   66990.000000
8320   1716147900000   66228.867188   65857.250000     -1   65857.250000
8327   1716154200000   66173.703125   66000.000000     -1   66000.000000
8343   1716168600000   66397.187500   66060.312500     -1   66060.312500
8392   1716212700000   67184.710938   66840.000000      1   67184.710938
8417   1716235200000   70421.242188   69672.039062      1   70421.242188
8480   1716291900000   71474.921875   71103.070312      1   71474.921875
8510   1716318900000   69944.398438   69245.000000      1   69944.398438
8518   1716326100000   69675.546875   69460.382812     -1   69460.382812

In [11]:
# --- run validation on STR columns ---
str_report = validate_markers(df, 'isSTR')

=== isSTR validation (10886 marks across full dataset) ===
  BOS violations : 2048
           timestamp           high            low  isSTR  price_at_mark
38     1708694100000   51042.429688   50925.019531     -1   50925.019531
50     1708704900000   50877.839844   50629.328125     -1   50629.328125
78     1708730100000   50805.578125   50521.000000     -1   50521.000000
94     1708744500000   50782.710938   50682.000000     -1   50682.000000
131    1708777800000   51065.140625   51032.339844     -1   51032.339844
145    1708790400000   51166.000000   51094.988281     -1   51094.988281
170    1708812900000   51666.000000   51605.558594      1   51666.000000
182    1708823700000   51513.539062   51438.878906     -1   51438.878906
195    1708835400000   51561.101562   51509.000000     -1   51509.000000
210    1708848900000   51777.640625   51729.988281      1   51777.640625
221    1708858800000   51627.179688   51553.289062     -1   51553.289062
229    1708866000000   51693.589844   51569.019531      1   51693.589844
267    1708900200000   51860.000000   51819.500000      1   51860.000000
275    1708907400000   51796.500000   51675.929688      1   51796.500000
297    1708927200000   51598.058594   51541.101562      1   51598.058594
337    1708963200000   53647.710938   52753.281250      1   53647.710938
353    1708977600000   54910.000000   54373.828125      1   54910.000000
362    1708985700000   54807.398438   54501.101562      1   54807.398438
383    1709004600000   56530.089844   56368.429688      1   56530.089844
416    1709034300000   56527.800781   56321.101562     -1   56321.101562
469    1709082000000   57101.101562   56878.980469      1   57101.101562
484    1709095500000   57271.441406   57060.019531      1   57271.441406
511    1709119800000   59494.058594   59134.000000      1   59494.058594
534    1709140500000   64000.000000   61130.000000      1   64000.000000
549    1709154000000   60510.000000   59797.570312     -1   59797.570312
588    1709189100000   63676.351562   62883.511719      1   63676.351562
614    1709212500000   62813.878906   62051.109375     -1   62051.109375
636    1709232300000   60841.101562   60364.699219     -1   60364.699219
689    1709280000000   61532.871094   61316.671875     -1   61316.671875
698    1709288100000   62188.000000   61917.660156      1   62188.000000
740    1709325900000   63114.230469   62414.441406      1   63114.230469
786    1709367300000   61959.820312   61779.609375     -1   61779.609375
833    1709409600000   62200.000000   61821.101562      1   62200.000000
845    1709420400000   61917.011719   61685.011719     -1   61685.011719
859    1709433000000   61793.210938   61642.390625     -1   61642.390625
875    1709447400000   62043.000000   61900.000000      1   62043.000000
913    1709481600000   62312.929688   62088.000000     -1   62088.000000
923    1709490600000   62863.679688   62595.281250      1   62863.679688
938    1709504100000   63231.878906   62820.011719      1   63231.878906
941    1709506800000   62886.910156   62700.000000     -1   62700.000000
953    1709517600000   63540.000000   63100.000000     -1   63100.000000
996    1709556300000   65157.140625   64868.660156     -1   64868.660156
1001   1709560800000   65275.031250   64533.671875     -1   64533.671875
1048   1709603100000   68686.796875   68244.343750      1   68686.796875
1101   1709650800000   69000.000000   67100.000000      1   69000.000000
1171   1709713800000   67641.101562   66776.046875      1   67641.101562
1237   1709773200000   66241.101562   65551.000000     -1   65551.000000
1256   1709790300000   65870.687500   65662.718750     -1   65662.718750
1266   1709799300000   67014.000000   66750.000000      1   67014.000000
1284   1709815500000   66753.929688   66575.523438     -1   66575.523438
1302   1709831700000   67980.000000   67571.648438      1   67980.000000
1309   1709838000000   67848.476562   67590.000000      1   67848.476562
1329   1709856000000   66883.453125   66757.000000     -1   66757.000000
1342   1709867700000   67254.218750   67069.890625      1   67254.218750
1363   1709886600000   67337.390625   67038.710938     -1   67038.710938
1377   1709899200000   67775.039062   67497.203125      1   67775.039062
1432   1709948700000   68020.000000   67861.101562     -1   67861.101562
1453   1709967600000   68541.101562   68396.328125      1   68541.101562
1467   1709980200000   68176.000000   67933.929688     -1   67933.929688
1477   1709989200000   68521.101562   68362.039062      1   68521.101562
1493   1710003600000   68171.640625   68000.000000     -1   68000.000000
1494   1710004500000   68121.406250   68000.000000     -1   68000.000000
1510   1710018900000   68366.046875   68209.593750     -1   68209.593750
1517   1710025200000   68433.171875   68310.000000      1   68433.171875
1518   1710026100000   68433.171875   68310.000000      1   68433.171875
1559   1710063000000   69756.000000   69162.000000     -1   69162.000000
1592   1710092700000   69600.000000   69411.070312      1   69600.000000
1656   1710150300000   71831.992188   71501.203125      1   71831.992188
1670   1710162900000   72380.000000   71928.007812      1   72380.000000
1689   1710180000000   72499.992188   72180.000000     -1   72180.000000
1782   1710263700000   69940.000000   68620.820312     -1   68620.820312
1815   1710293400000   72100.000000   71757.046875      1   72100.000000
1822   1710299700000   72217.789062   71999.882812      1   72217.789062
1828   1710305100000   72210.000000   72141.101562      1   72210.000000
1877   1710349200000   73180.000000   72845.000000      1   73180.000000
1883   1710354600000   73263.992188   72944.000000      1   73263.992188
1890   1710360900000   73410.218750   73161.382812      1   73410.218750
1895   1710365400000   73361.007812   72940.000000      1   73361.007812
1953   1710417600000   73047.156250   72820.000000      1   73047.156250
1997   1710457200000   71709.898438   71401.101562      1   71709.898438
2019   1710477000000   68278.406250   66904.976562     -1   66904.976562
2055   1710509400000   68285.203125   67424.789062     -1   67424.789062
2061   1710514800000   68746.687500   68310.460938      1   68746.687500
2077   1710529200000   70650.000000   70081.101562      1   70650.000000
2153   1710597600000   68146.398438   67524.000000     -1   67524.000000
2172   1710614700000   67102.507812   66670.000000     -1   66670.000000
2180   1710621900000   67538.492188   67107.546875      1   67538.492188
2187   1710628200000   66786.437500   66477.000000      1   66786.437500
2259   1710693000000   68385.820312   68045.500000      1   68385.820312
2264   1710697500000   68693.750000   68180.000000      1   68693.750000
2341   1710766800000   68627.812500   68250.000000      1   68627.812500
2365   1710788400000   67187.171875   66870.953125     -1   66870.953125
2375   1710797400000   67896.546875   67517.726562      1   67896.546875
2414   1710832500000   64528.000000   63577.000000     -1   63577.000000
2421   1710838800000   63808.218750   62982.800781     -1   62982.800781
2472   1710884700000   64109.980469   63691.890625      1   64109.980469
2530   1710936900000   64353.570312   63683.871094      1   64353.570312
2592   1710992700000   66979.070312   66340.000000     -1   66340.000000
2598   1710998100000   66550.773438   66072.203125     -1   66072.203125
2610   1711008900000   67659.531250   67300.000000      1   67659.531250
2657   1711051200000   65489.609375   64529.011719     -1   64529.011719
2665   1711058400000   65857.273438   65600.000000      1   65857.273438
2697   1711087200000   66649.617188   66337.773438      1   66649.617188
2732   1711118700000   63088.480469   62601.109375     -1   62601.109375
2752   1711136700000   64126.089844   63772.429688      1   64126.089844
2777   1711159200000   64374.910156   63910.000000      1   64374.910156
2839   1711215000000   65999.000000   65627.070312      1   65999.000000
2864   1711237500000   64450.000000   63861.660156     -1   63861.660156
2883   1711254600000   64061.191406   63772.289062     -1   63772.289062
2908   1711277100000   65368.660156   65090.000000      1   65368.660156
2917   1711285200000   65825.000000   65450.019531      1   65825.000000
2929   1711296000000   65838.882812   65596.000000      1   65838.882812
2958   1711322100000   67628.687500   67300.773438      1   67628.687500
2992   1711352700000   67024.000000   66710.000000     -1   66710.000000
3008   1711367100000   66887.640625   66760.000000     -1   66760.000000
3041   1711396800000   71150.000000   70737.382812      1   71150.000000
3073   1711425600000   70665.828125   70401.109375      1   70665.828125
3154   1711498500000   70119.398438   69840.000000     -1   69840.000000
3217   1711555200000   69310.000000   68359.179688     -1   68359.179688
3247   1711582200000   69202.000000   69072.398438     -1   69072.398438
3385   1711706400000   69883.578125   69566.000000     -1   69566.000000
3412   1711730700000   69498.000000   69078.617188     -1   69078.617188
3453   1711767600000   70042.187500   69906.132812      1   70042.187500
3527   1711834200000   69746.257812   69621.968750     -1   69621.968750
3579   1711881000000   70281.406250   70214.523438     -1   70214.523438
3703   1711992600000   68524.726562   68201.117188     -1   68201.117188
3719   1712007000000   69900.000000   69631.109375      1   69900.000000
3727   1712014200000   69876.039062   69758.992188      1   69876.039062
3739   1712025000000   68536.000000   66000.000000     -1   66000.000000
3750   1712034900000   66557.750000   66120.750000     -1   66120.750000
3756   1712040300000   67120.000000   66830.156250      1   67120.000000
3775   1712057400000   65536.921875   65075.000000     -1   65075.000000
3783   1712064600000   65116.101562   64588.578125     -1   64588.578125
3807   1712086200000   66200.000000   65851.070312      1   66200.000000
3843   1712118600000   66478.593750   66216.000000      1   66478.593750
3879   1712151000000   65957.101562   65635.007812     -1   65635.007812
3938   1712204100000   65548.039062   65064.519531     -1   65064.519531
3962   1712225700000   66468.992188   66205.203125      1   66468.992188
3986   1712247300000   68188.000000   67678.398438      1   68188.000000
3993   1712253600000   69309.906250   68705.882812      1   69309.906250
3999   1712259000000   69086.226562   68684.062500      1   69086.226562
4007   1712266200000   67955.976562   67495.000000     -1   67495.000000
4081   1712332800000   68380.000000   68034.843750      1   68380.000000
4144   1712389500000   68189.328125   67953.148438      1   68189.328125
4157   1712401200000   67904.351562   67717.218750      1   67904.351562
4163   1712406600000   67796.687500   67663.226562      1   67796.687500
4189   1712430000000   68415.000000   68218.000000      1   68415.000000
4191   1712431800000   68415.000000   68290.898438      1   68415.000000
4201   1712440800000   68539.187500   68286.328125     -1   68286.328125
4217   1712455200000   69777.000000   69472.617188      1   69777.000000
4227   1712464200000   69278.578125   69053.968750     -1   69053.968750
4235   1712471400000   69298.679688   69110.812500     -1   69110.812500
4288   1712519100000   69320.000000   68849.773438     -1   68849.773438
4452   1712666700000   70977.000000   70690.000000      1   70977.000000
4469   1712682000000   68791.757812   68210.000000     -1   68210.000000
4477   1712689200000   68879.226562   68656.078125     -1   68656.078125
4552   1712756700000   68313.101562   67518.000000     -1   67518.000000
4566   1712769300000   69910.960938   69195.851562      1   69910.960938
4616   1712814300000   70600.000000   70444.000000     -1   70444.000000
4659   1712853000000   69845.757812   69574.882812     -1   69574.882812
4695   1712885400000   70258.187500   70113.601562     -1   70113.601562
4719   1712907000000   70865.929688   70566.023438     -1   70566.023438
4758   1712942100000   68711.992188   67444.000000     -1   67444.000000
4763   1712946600000   67889.898438   65086.859375     -1   65086.859375
4813   1712991600000   67563.656250   67366.632812      1   67563.656250
4820   1712997900000   67285.382812   67090.828125     -1   67090.828125
4893   1713063600000   63150.000000   62134.000000     -1   62134.000000
4966   1713129300000   63815.148438   63326.421875     -1   63326.421875
4987   1713148200000   65272.398438   64937.011719     -1   64937.011719
5021   1713178800000   66720.640625   66191.476562      1   66720.640625
5149   1713294000000   63094.800781   62843.921875      1   63094.800781
5166   1713309300000   63876.640625   63690.019531      1   63876.640625
5177   1713319200000   64295.000000   63989.160156      1   64295.000000
5186   1713327300000   63817.179688   63672.261719     -1   63672.261719
5209   1713348000000   63338.718750   62752.308594     -1   62752.308594
5252   1713386700000   61245.929688   60777.000000     -1   60777.000000
5261   1713394800000   61763.070312   61544.109375      1   61763.070312
5310   1713438900000   63072.269531   62400.000000      1   63072.269531
5337   1713463200000   62907.679688   62310.031250     -1   62310.031250
5426   1713543300000   64276.621094   63506.570312     -1   63506.570312
5444   1713559500000   64044.121094   63677.359375     -1   63677.359375
5496   1713606300000   63646.000000   63277.000000     -1   63277.000000
5583   1713684600000   65086.121094   64899.839844     -1   64899.839844
5654   1713748500000   65640.000000   64908.390625      1   65640.000000
5672   1713764700000   66414.812500   66064.453125      1   66414.812500
5677   1713769200000   66479.796875   66097.359375      1   66479.796875
5683   1713774600000   66204.437500   66035.171875      1   66204.437500
5703   1713792600000   66109.398438   65693.976562     -1   65693.976562
5796   1713876300000   66134.921875   65765.812500     -1   65765.812500
5922   1713989700000   64018.449219   63606.058594     -1   63606.058594
5940   1714005900000   64741.468750   64538.000000      1   64741.468750
5958   1714022100000   64234.148438   64025.500000     -1   64025.500000
6010   1714068900000   64975.000000   64649.988281      1   64975.000000
6017   1714075200000   64992.000000   64489.300781     -1   64489.300781
6029   1714086000000   64747.121094   64469.988281      1   64747.121094
6062   1714115700000   64610.820312   64279.570312      1   64610.820312
6120   1714167900000   64080.558594   63949.199219      1   64080.558594
6147   1714192200000   63175.000000   63020.281250      1   63175.000000
6155   1714199400000   63024.511719   62865.460938     -1   62865.460938
6173   1714215600000   62857.148438   62673.371094     -1   62673.371094
6186   1714227300000   63408.531250   63154.101562      1   63408.531250
6197   1714237200000   62866.519531   62750.000000     -1   62750.000000
6238   1714274100000   64370.000000   64026.218750      1   64370.000000
6266   1714299300000   63645.511719   63345.550781     -1   63345.550781
6272   1714304700000   63503.699219   63394.679688     -1   63394.679688
6300   1714329900000   63976.000000   63762.000000      1   63976.000000
6317   1714345200000   63151.058594   62781.000000     -1   62781.000000
6327   1714354200000   63367.050781   63167.691406      1   63367.050781
6343   1714368600000   62403.750000   62059.269531     -1   62059.269531
6348   1714373100000   62266.820312   61923.128906     -1   61923.128906
6362   1714385700000   62673.179688   62506.050781      1   62673.179688
6373   1714395600000   62698.550781   62511.429688      1   62698.550781
6439   1714455000000   63376.019531   63069.679688     -1   63069.679688
6465   1714478400000   61288.699219   60737.449219     -1   60737.449219
6474   1714486500000   60934.480469   60546.218750     -1   60546.218750
6512   1714520700000   60924.160156   60631.179688      1   60924.160156
6522   1714529700000   59871.101562   59590.000000     -1   59590.000000
6651   1714645800000   57776.191406   57561.140625     -1   57561.140625
6689   1714680000000   59431.101562   59191.660156      1   59431.101562
6700   1714689900000   59454.171875   59256.859375      1   59454.171875
6824   1714801500000   63450.000000   63124.539062      1   63450.000000
6840   1714815900000   63179.808594   63055.550781     -1   63055.550781
6881   1714852800000   64240.761719   63921.171875      1   64240.761719
6892   1714862700000   63720.699219   63569.988281     -1   63569.988281
6979   1714941000000   63724.000000   63582.078125     -1   63582.078125
7026   1714983300000   65500.000000   64462.480469      1   65500.000000
7028   1714985100000   65500.000000   65064.160156      1   65500.000000
7044   1714999500000   63785.589844   63343.859375     -1   63343.859375
7136   1715082300000   63620.871094   63358.000000     -1   63358.000000
7182   1715123700000   62446.351562   62261.000000     -1   62261.000000
7198   1715138100000   62780.230469   62588.000000     -1   62588.000000
7210   1715148900000   62540.000000   62135.480469     -1   62135.480469
7216   1715154300000   62359.988281   62020.089844     -1   62020.089844
7239   1715175000000   62087.449219   61761.000000     -1   61761.000000
7325   1715252400000   60956.921875   60630.000000     -1   60630.000000
7394   1715314500000   63008.000000   62850.000000      1   63008.000000
7441   1715356800000   61147.000000   60255.000000     -1   60255.000000
7448   1715363100000   60635.121094   60187.121094     -1   60187.121094
7505   1715414400000   61058.750000   60897.148438      1   61058.750000
7513   1715421600000   60904.429688   60850.000000      1   60904.429688
7524   1715431500000   60758.828125   60643.941406     -1   60643.941406
7545   1715450400000   61110.011719   61016.000000     -1   61016.000000
7588   1715489100000   61120.000000   61006.011719      1   61120.000000
7619   1715517000000   61168.031250   61090.000000     -1   61090.000000
7628   1715525100000   61186.628906   61124.769531     -1   61124.769531
7646   1715541300000   61355.539062   61209.589844     -1   61209.589844
7654   1715548500000   61310.000000   60910.578125     -1   60910.578125
7714   1715602500000   62749.769531   62399.351562     -1   62399.351562
7719   1715607000000   62845.000000   62600.789062     -1   62600.789062
7795   1715675400000   61925.210938   61697.050781     -1   61697.050781
7802   1715681700000   61676.890625   61520.890625     -1   61520.890625
7818   1715696100000   62030.238281   61142.769531     -1   61142.769531
7847   1715722200000   61776.121094   61472.410156     -1   61472.410156
7922   1715789700000   65150.000000   64758.011719      1   65150.000000
7935   1715801400000   66419.148438   65834.867188      1   66419.148438
7953   1715817600000   66666.000000   66206.500000      1   66666.000000
8023   1715880600000   64918.910156   64602.769531     -1   64602.769531
8048   1715903100000   65310.000000   65187.500000     -1   65187.500000
8093   1715943600000   66564.226562   66202.460938      1   66564.226562
8171   1716013800000   66817.859375   66730.000000     -1   66730.000000
8221   1716058800000   66820.000000   66771.757812     -1   66771.757812
8295   1716125400000   66940.000000   66677.000000     -1   66677.000000
8305   1716134400000   66990.000000   66850.210938      1   66990.000000
8320   1716147900000   66228.867188   65857.250000     -1   65857.250000
8327   1716154200000   66173.703125   66000.000000     -1   66000.000000
8343   1716168600000   66397.187500   66060.312500     -1   66060.312500
8392   1716212700000   67184.710938   66840.000000      1   67184.710938
8417   1716235200000   70421.242188   69672.039062      1   70421.242188
8480   1716291900000   71474.921875   71103.070312      1   71474.921875
8510   1716318900000   69944.398438   69245.000000      1   69944.398438
8518   1716326100000   69675.546875   69460.382812     -1   69460.382812

In [12]:
# --- run validation on ITR columns ---
itr_report = validate_markers(df, 'isITR')

=== isITR validation (3644 marks across full dataset) ===
  BOS violations : 0  — alternation OK
  Order violations: 0  — price ordering OK
  Valid: True

In [13]:
# --- run validation on LTR columns ---
ltr_report = validate_markers(df, 'isLTR')

=== isLTR validation (1169 marks across full dataset) ===
  BOS violations : 0  — alternation OK
  Order violations: 0  — price ordering OK
  Valid: True

In [ ]:
# Export marker to json visulize the data on Chart

# onchart data
```json
onchart : [{
    name: "Marker",
    type: "Marker",
    data: marking,
    settings: {
        "z-index": 5,
        "legend": false
    }
}]
```

where marking is

```json
[
     1771612200000,  // timestamp
     'buy',          // marker type: 'buy' | 'sell' | 'str' | 'itr' | 'ltr'
     67527.01,       // value at mark
     "lo"            // legend (optional)
], ...
```

In [ ]:
def exportJsonWithMarker(df, out_path):
    itr_df = df[df['isITR'] != 0][['timestamp', 'isITR', 'high', 'low']]

    data = [
        [
            int(row['timestamp']),
            'itr',
            float(row['high']) if row['isITR'] == 1 else float(row['low']),
            ''
        ]
        for _, row in itr_df.iterrows()
    ]

    payload = {
        "onchart": [{
            "name": "Marker",
            "type": "Marker",
            "data": data,
            "settings": {
                "z-index": 5,
                "legend": False
            }
        }]
    }

    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, 'w') as f:
        json.dump(payload, f)

    print(f"Exported {len(data)} markers to {out_path}")


# execute
OUT_PATH = Path.cwd().parents[1] / "data" / "bigData" / "15m-marker.json"
exportJsonWithMarker(df, OUT_PATH)